- name: deploy-golang-application
  hosts: test1
  become: yes
  become_user: admin
  tasks:
    - name: apt-golang
      apt: 
        name: golang
        state: latest
    - name: apt-git
      apt:
        name: git
        state: latest
    - name: pull-app
      git:
        repo: git@github.com:sergodk/goservice.git
        dest: goservice/
        force: yes
        update: yes
    - name: build-app
      ansible.builtin.shell:
        cmd: go build main.go
        chdir: goservice/
    - name: run-app
      ansible.builtin.shell:
        cmd: ./main
        chdir: goservice/
